name: '3rd-prebuild workflow'


on: [push]

jobs:
  Build-Libs-Linux-Ubuntu:
    name: 'Build-Libs-Linux-Ubuntu'
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [x86, x86_64, arm32, arm64]
      fail-fast: false

    steps:

    - name: Set up build environment
      uses: awalsh128/cache-apt-pkgs-action@latest
      if: matrix.arch != 'arm32' && matrix.arch != 'arm64'  
      with:
        packages: gcc-multilib g++-multilib
        version: 1.0
        
    - name: Set up build environment
      uses: awalsh128/cache-apt-pkgs-action@latest
      if: matrix.arch != 'x86' && matrix.arch != 'x86_64'  
      with:
        packages: gcc-arm-linux-gnueabihf gcc-aarch64-linux-gnu
        version: 1.0    

    - name: 'Get sources'
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 10

    - name: 'Get openssl'
      uses: actions/checkout@v3
      with:
        repository: openssl/openssl
        ref: OpenSSL_1_1_1t
        path: openssl

    - name: Build OpenSSL
      run: |
        cd openssl
        case "${{ matrix.arch }}" in
          x86) ./Configure no-tests linux-x86 shared;;
          x86_64) ./Configure no-tests linux-x86_64 shared ;;
          arm32) ./Configure no-tests linux-armv4 --cross-compile-prefix=arm-linux-gnueabihf- shared ;;
          arm64) ./Configure no-tests linux-aarch64 --cross-compile-prefix=aarch64-linux-gnu- shared ;;
        esac
        make



