name: build

on: [push]
    

jobs:
      
  Build-Libs-WireGuard-Windows:
    name: 'Build-Libs-WireGuard-Windows'
    runs-on: windows-latest
    if: |
      contains(github.event.head_commit.message, '[all]') ||
      contains(github.event.head_commit.message, '[windows]') ||
      contains(github.event.head_commit.message, '[windows-wireguard]') ||
      contains(github.event.head_commit.message, '[wireguard]')      

    steps:
     
    - name: 'Setup ccache'
      uses: hendrikmuhs/ccache-action@v1.2
          
    - name: 'Get sources'
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 10

    - name: 'Get Wireguard'
      uses: actions/checkout@v3
      with:
        repository: WireGuard/wireguard-windows
        ref: master
        path: windows/wireguard-windows

    - name: 'Build WireGuard binary'
      working-directory: windows/wireguard-windows
      run: |
        cmd /c build.bat
        cmd /c embeddable-dll-service\build.bat
        mkdir build
        move embeddable-dll-service\amd64 build\amd64
        move embeddable-dll-service\arm64 build\arm64
        move embeddable-dll-service\x86 build\x86
        move .deps\wireguard-nt\bin\amd64\wireguard.dll build\amd64
        move .deps\wireguard-nt\bin\arm64\wireguard.dll build\arm64
        move .deps\wireguard-nt\bin\x86\wireguard.dll build\x86
    
    - name: Archive WG Windows 
      uses: actions/upload-artifact@v3
      with:
        retention-days: 1
        name: windows-wireguard
        path: windows/wireguard-windows/build           
        


