name: build

on: [push]
    

jobs:
      
  Build-Libs-Cloak-Windows:
    name: 'Build-Libs-Cloak-Windows'
    runs-on: ubuntu-latest
    if: |
      contains(github.event.head_commit.message, '[all]') ||
      contains(github.event.head_commit.message, '[windows]') ||
      contains(github.event.head_commit.message, '[linux]') ||
      contains(github.event.head_commit.message, '[cloak]')

    steps:
  
    - name: 'Install GO'
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.3

    - name: 'Setup ccache'
      uses: hendrikmuhs/ccache-action@v1.2
          
    - name: 'Get sources'
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 10

    - name: 'Get Cloak'
      uses: actions/checkout@v3
      with:
        repository: amnezia-vpn/Cloak
        ref: master-amnezia
        path: windows/Cloak

    - name: 'Build Cloak binary'
      working-directory: windows/Cloak
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        v=${GITHUB_REF#refs/*/} ./release.sh


