name: '3rd-prebuild workflow'


on: [push]

jobs:
  Build-Libs-OpenSSL-Win:
    name: 'Build-OpenSSL-Lib-Windows'
    runs-on: windows-latest
    
    strategy:
      matrix:
        arch:
          - amd64
          - amd64_x86
          
    steps:
      - name: 'Get openssl'
        uses: actions/checkout@v3
        with:
          repository: openssl/openssl
          ref: OpenSSL_1_1_1t
          path: openssl
      
      - name: Setup msbuild environment    
        uses: ilammy/msvc-dev-cmd@v1
        with:
          arch: ${{ matrix.arch }}
      - uses: ilammy/setup-nasm@v1.2.1
        name: Install NASM
      - uses: shogo82148/actions-setup-perl@v1
        name: Install PERL
        with:
          distribution: strawberry
      - name: Build OpenSSL x86
        if: matrix.arch == 'amd64_x86'
        run: |
          cd openssl

          perl Configure no-tests shared VC-WIN32
          nmake
          mkdir out32
          move libcrypto.lib out32
          move libcrypto-1_1.dll out32
          move libssl.lib out32
          move libssl-1_1.dll out32 
      - name: Build OpenSSL x64
        if: matrix.arch == 'amd64'
        run: |
          cd openssl

          perl Configure no-tests shared VC-WIN64A
          nmake
          mkdir out64
          move libcrypto.lib out64
          move libssl.lib out64
          move libcrypto-1_1-x64.dll out64
          move libssl-1_1-x64.dll out64

 

