name: build

on: [push]
    

jobs:
      
  Build-Libs-Cloak-Windows:
    name: 'Build-Libs-Cloak-Windows'
    runs-on: ubuntu-latest

    steps:
  
    - name: 'Install GO'
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.3

    - name: 'Setup ccache'
      uses: hendrikmuhs/ccache-action@v1.2
          
    - name: 'Get sources'
      uses: actions/checkout@v3
      with:
        submodules: 'true'
        fetch-depth: 10

    - name: 'Build Cloak binary'
      working-directory: windows/Cloak
      run: |
        export PATH=${PATH}:`go env GOPATH`/bin
        v=${GITHUB_REF#refs/*/} ./release.sh


